server:
  port: 8888

spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: ssh@host-name
          ignore-local-ssh-settings: true
          private-key: | 
                        *********